language: node_js # set Travis language
node_js:
  - lts/* # use latest LTS node release
notifications:
  email: false
jobs:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: osx
branches:
  only:
  - master
  - dev