language: node_js # set Travis language
node_js:
  - lts/* # use latest LTS node release
notifications:
  email: false
jobs:
  include:
    - os: linux
      dist: bionic # use Ubuntu Bionic (18.04)
    - os: osx
      osx_image: xcode11.4
      script: npm run test -- --mac --win # test for both windows and mac
branches:
  only:
    - master
    - dev
